version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=admin
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: mongod --auth
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

  app:
    build: .
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules


volumes:
  mongodb_data_container:
